### ISSUE TITLE
Action always passes without detecting secrets

### ISSUE THREAD

**Issue by sammcj** [edplato/trufflehog-actions-scan#17]
When I try to use this action, it completes without error but does not find any secrets (regex or high entropy).

I have:

- Ensured I'm using checkout@v2 with `fetch-depth: "0"` before the trufflehog step.
- Confirmed with a `ls -laR` that the git repo is indeed checked out in the PWD.
- Explicitly specifying `--rules`, `--entropy` `--max_depth`.
- Running trufflehog locally in the same git repo and it works as expected (detects secrets).

Configuration:

```
  TruffleHog:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - run: ls -laR
    - uses: edplato/trufflehog-actions-scan@master
      with:
        scanArguments: "--regex --entropy=true --max_depth=1000 --rules regexes.json"
```

Output from Action with a repo that contains some fake secrets:

_Note that it doesn't look like the action is even running trufflehog_

![Screen Shot 2021-12-15 at 10 53 18 am](https://user-images.githubusercontent.com/862951/146097815-e68703d1-fb84-4e57-a0b6-e725d0e0d7a4.jpg)

Example output from running Trufflehog locally with the same repo:

```
trufflehog --regex --entropy=false --max_depth=1000 --rules regexes.json file://$(pwd)

-----BEGIN EC PRIVATE KEY-----
~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~
Reason: PGP private key block
Date: 2021-12-09 10:43:49
Hash: 87b860ae90f535ebc11646e9753be23894844966
Filepath: .gitleaks.toml
Branch: origin/secrets_scanning
Commit: add mvp of trufflehog secrets scanning

-----BEGIN PGP PRIVATE KEY BLOCK-----
~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~
Reason: Generic Secret
Date: 2021-12-09 10:43:49
Hash: 87b860ae90f535ebc11646e9753be23894844966
Filepath: fakesecretitems/testbadcode.py
Branch: origin/secrets_scanning
Commit: add mvp of trufflehog secrets scanning

secret : "lolasifidsaveapasswordinplaintextbro"
```
