### ISSUE TITLE
Exclude some detector type or file path

### ISSUE THREAD

**Issue by sjgupta19** [edplato/trufflehog-actions-scan#20]
Hi, how can I exclude some paths or a particular detector type from scanning since it could be a known secret? 
Below is my action that I am using - 
  ```
 - name: checkout-pr
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: get-branch
        run: |
          echo "BRANCH=$(git branch --show-current)" >> $GITHUB_ENV   
      - name: Run secret scanner
        uses: edplato/trufflehog-actions-scan@v0.9l-beta
        with:
            scanArguments: "--regex --only-verified --entropy=False --max_depth=100 --branch ${{ env.BRANCH }} --rules .github/secrets-scanner/regexes.json"
```
