### ISSUE TITLE
No output when run on known problem project

### ISSUE THREAD

**Issue by shehackspurple** [edplato/trufflehog-actions-scan#4]
Hi,

I'm creating an intentionally vulnerable repo/project to use for a workshop, and I'd like to demo trufflehog, using github actions.  I run trufflehog locally on the project folder and it lights up like a Christmas tree, it finds all the secrets.  However, when I run it with the GitHub Action it says it ran successfully, but there is no output.  I'm confused. 

I tried adding another fake private key, checking it in, which triggers my DotNetDemo.yml actions, and it still has no input.  I know truffle hog would find this as it finds this, and more, locally.

Here's my workflow file: https://github.com/shehackspurple/dotnetcore-webapp/blob/master/.github/workflows/DotNetDemo.yml

Thanks for making this action, looking forward to automating this.

Tanya

**Comment by edplato** [comment]
Hi. It appears the default `trufflehog` regex rules didn't account for the key you are using to throw an error. I added a few custom regex rules in addition to the default ones to catch this key in the future. Please try switch from branch `master` to `custom-rules` to confirm this fix will work for you and I will incorporate this into the action.

**Comment by shehackspurple** [comment]
You changes worked!  It now finds my key.  Could you please merge it to master?

Thank you!

**Comment by edplato** [comment]
I have merged this fix. You will need to set custom `scanArguments` to use the custom regex json:
```yaml
steps:
- uses: actions/checkout@master
- name: trufflehog-actions-scan
  uses: edplato/trufflehog-actions-scan@master
  with:
    scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*

```
